### ISSUE TITLE
Static brick issue

### ISSUE THREAD

**Issue by tcthanh** [passy/angular-masonry#102]
without that template brick
<div class="masonry-brick pin" ng-repeat="pin in pins">...</div>

i have another static brick with any content like this
<div class="masonry-brick other-brick">other content</div>

you can see below pictures.
![screenshot from 2015-01-12 20 18 39](https://cloud.githubusercontent.com/assets/6198655/5703364/51444728-9a98-11e4-9a32-4f96107a0f7e.png)
![screenshot from 2015-01-12 20 18 44](https://cloud.githubusercontent.com/assets/6198655/5703365/51487898-9a98-11e4-9e5a-247fbef6f8be.png)

That seem not working correctly...
Can you tell me a solution for that?

**Comment by tcthanh** [comment]
Block "Invite friends to pinterest" is my another static brick...
Please help me, tks a lot.

**Comment by rubencosta** [comment]
+1

**Comment by ArniDzhan** [comment]
We have the same issue,
managed to solve it using ng-repeat on element instead of just having a static html block.
I would call this solution a hack, hope project collaborators can offer a proper way to to this.

in my controller I have data set returned with actual items data and one with dummy data for static element
````javascript
$scope.contentData = response;
$scope.singleItem = JSON.parse('[{"dummy":"content"}]');
````
in a view
````html
<article class="pinbox masonry-brick" ng-repeat="content in singleItem">
    <div class="excerpt">
        doesn't have to use content.variables and gets output only once since singleItem has one item
    </div>
</article>
<article class="pinbox masonry-brick" ng-repeat="look in contentData">
    <div class="excerpt">
        {{look.description}}
    </div>
</article>
````

**Comment by passy** [comment]
Thanks for the input, @ArniDzhan. Closing now.
