### ISSUE TITLE
static masonry brick with ng-repeat 

### ISSUE THREAD

**Issue by knulan** [passy/angular-masonry#105]
I have a problem with block position. I have static block before ng-repeat 
<pre>
div masonry load-images="true" column-width="200" preserve-order>
div class="masonry-brick"></div>
div class="masonry-brick" ng-repeat="userAlbum in userAlbums"></div>
/div>
</pre>
and i got
![1](https://cloud.githubusercontent.com/assets/5101556/5775935/50862be6-9d89-11e4-8080-212050834ad9.jpg)

Simple fix of this bug is to put static block in another ng-repeat:
<pre>
div masonry load-images="true" column-width="200" preserve-order>
div class="masonry-brick" ng-repeat="block in blocks"></div>
div class="masonry-brick" ng-repeat="userAlbum in userAlbums"></div>
/div>
</pre>
and in controller simple create a scope:<pre> $scope.blocks = [{'title':'Album1'}];</pre>

result is:
![2](https://cloud.githubusercontent.com/assets/5101556/5775954/a9d6712e-9d89-11e4-87fe-2f2e4d48133b.JPG)
Is it possible to fix this bug without adding second ng-repeat?

**Comment by leozero** [comment]
You can fix this bug with a simple ng-if="true" to replace your ng-repeat, but thank you, I resolve my bug with your solution and next I tried ng-if="true" .

**Comment by knulan** [comment]
thanks, it worked!
