### ISSUE TITLE
Publish to NPM :)

### ISSUE THREAD

**Issue by Reklino** [passy/angular-masonry#113]
Well done! I would love to have access to this via an NPM package instead of just bower.

**Comment by passy** [comment]
@Reklino Would you be able to check if #114 works for you if you `npm link` to it?

**Comment by varmint09** [comment]
Hello, 

I would also love a version published to npm, and I think it may also need ngAnotate too as I uglify code, where are we at with this and how would I use it?

Regards,

Darryl

**Comment by varmint09** [comment]
Also, I would ideally like to use this with bootstrap 3,

something like

```html
<div class="row" masonry>
  <div class="col-md-4" masonry-brick>
   content is text and or image
  </div>
</div>
```

**Comment by varmint09** [comment]
Any news?

**Comment by varmint09** [comment]
Still no news? Ever so sorry to chase.

**Comment by passy** [comment]
@varmint09 Sorry, please keep chasing. Pretty busy at the moment, I'm afraid. :(
