### ISSUE TITLE
Update dependancies for Masonry and Angular

### ISSUE THREAD

**Issue by tjshipe** [passy/angular-masonry#121]
Can we update the bower package dependancies for Angular to include 1.4? I saw a pull request for this was closed, but when I change it to 1.4.0 it works with no issues.

**Comment by passy** [comment]
Yes, would you be interested in submitting a pull request for that update?

**Comment by vrouet** [comment]
I'm wondering why nobody ended up doing that, as it seems toi only require bumping the required version in bower.json.
If I heve a go at it and check all tests are passing, do you think I can get a pull request accepted and a new version released rapidly?

**Comment by passy** [comment]
@vrouet Yup, I think so. :)
