### ISSUE TITLE
images reload twice

### ISSUE THREAD

**Issue by mroker242** [passy/angular-masonry#127]
When you go to the page the images reload twice, then they are fine. I obviously only want them to load once. I've tried different options but just can't figure this one out. It's like they reload but I don't see any options I have to do this.

Here is a sample.

http://192.185.87.92/~ysaguirre/#/gallery

            <img ng-src="{{ brick.Thumburl }}" ng-class = "{highlight:hover}" ng-mouseenter="hover = true" ng-mouseleave="hover = false" alt="A masonry brick" class="img-thumbnail">
        </a>
    </div>

</div> -->

**Comment by prugel** [comment]
You need stylesheet.
```
        <style>
            .masonry-brick {
                margin: 1em;
                display: none;
            }
            .masonry-brick.loaded {
                display: block;
            }
        </style>
```

**Comment by mroker242** [comment]
Perfect. This works perfectly.
