### ISSUE TITLE
Project not built for tag 0.14.0

### ISSUE THREAD

**Issue by Yuyuu** [passy/angular-masonry#147]
Hello,
I think you forgot to build the project when releasing 0.14.0. Therefore the (dist) files we get are from 0.13.0.

**Comment by passy** [comment]
Sorry, not sure why those weren't committed. I'll release a 0.14.1 in a few.

**Comment by passy** [comment]
Thanks for the report. Fixed via https://github.com/passy/angular-masonry/commit/192efaa5cb6d07910c6491c8b32e5cf59ae9e680
