### ISSUE TITLE
Error: [$compile:ctreq] Controller 'masonry', required by directive 'masonryBrick', can't be found!

### ISSUE THREAD

**Issue by longgeek** [passy/angular-masonry#148]
how to fix？

**Comment by JohnnyTheTank** [comment]
## Example

See the [homepage](http://passy.github.io/angular-masonry) for a live example.

```html
<div masonry>
    <div class="masonry-brick" ng-repeat="brick in bricks">
        <img ng-src="{{ brick.src }}" alt="A masonry brick">
    </div>
</div>
```

**Comment by longgeek** [comment]
@JohnnyTheTank Thank you very much for your reply。

my config.js:

    .state('learn', {                                                                                                                                                                                                                         
        url: "/learn",                                                                                                                                                                                                                        
        templateUrl: "app/views/learn/learn.html",                                                                                                                                                                                            
        data: { pageTitle: 'All Learn Courses', specialClass: 'landing-page' },                                                                                                                                                               
        controller: LearnController,                                                                                                                                                                                                          
        resolve: {                                                                                                                                                                                                                            
            loadPlugin: function ($ocLazyLoad) {                                                                                                                                                                                              
                return $ocLazyLoad.load([                                                                                                                                                                                                     
                    {                                                                                                                                                                                                                         
                        name: 'wu.masonry',                                                                                                                                                                                                   
                    }                                                                                                                                                                                                                         
                ]);                                                                                                                                                                                                                           
            }                                                                                                                                                                                                                                 
        }                                                                                                                                                                                                                                     
    }) 
    .state('learn.plan', {                                                                                                                                                                                                                    
        url: "/plan",                                                                                                                                                                                                                         
        templateUrl: "app/views/learn/plan/list.html",                                                                                                                                                                                        
        data: { pageTitle: 'Plan Lists', specialClass: 'landing-page' },                                                                                                                                                                      
        controller: PlanListController,                                                                                                                                                                                                       
    })                                                                                                                                                                                                                                        
    .state('learn.course', {                                                                                                                                                                                                                  
        url: "/course",                                                                                                                                                                                                                       
        templateUrl: "app/views/learn/course/list.html",                                                                                                                                                                                      
        data: { pageTitle: 'Course Lists', specialClass: 'landing-page' },                                                                                                                                                                    
        controller: CourseListController,                                                                                                                                                                                                     
    })                                                                                                                                                                                                                                        
    .state('learn.plan.detail', {                                                                                                                                                                                                             
        url: "/detail/?pid",                                                                                                                                                                                                                  
        templateUrl: "app/views/learn/plan/detail.html",                                                                                                                                                                                      
        data: { pageTitle: 'Plan Detail', specialClass: 'landing-page learn-plan-detail' },                                                                                                                                                   
        controller: PlanDetailController,                                                                                                                                                                                                     
    })                                                                                                                                                                                                                                        
    .state('learn.course.detail', {                                                                                                                                                                                                           
        url: "/detail/?cid",                                                                                                                                                                                                                  
        templateUrl: "app/views/learn/course/detail.html",                                                                                                                                                                                    
        data: { pageTitle: 'Course Detail', specialClass: 'landing-page learn-course-detail' },                                                                                                                                               
        controller: CourseDetailController,                                                                                                                                                                                                   
    }) 
    
    
in the learn.html:

	...
	
	<div masonry="{ gutter: 20 }" load-images="false" preserve-order column-width="300" reload-on-resize>
	    <div class="masonry-brick" ng-repeat="course in courses">
	    	{{ course }}
	    </div>
	</div>
	
	...
	
Only learn page I use the masonry, but I visit /learn/plan、/learn/course、/learn/plan/detail.. /learn/course/detail these url will throw this exception? Is "masonry-brick" must also exist in the sub-pages?

**Comment by longgeek** [comment]
I think I've found the solution，in learn.html:

    <div masonry="{ gutter: 20 }" load-images="false" preserve-order column-width="300" reload-on-resize  oc-lazy-load="wu.masonry">
        <div class="masonry-brick" ng-repeat="course in courses">
            {{ course }}
        </div>
    </div>

use  oc-lazy-load="wu.masonry" directive.
