### ISSUE TITLE
Multiple directive

### ISSUE THREAD

**Issue by Sajgoniarz** [passy/angular-masonry#150]
Hello! Is it possible to make masonry-brick working with my custom directive? If yes, how to achieve this?

**Comment by passy** [comment]
That's a bit too broad. What are you planning to do?

**Comment by wembernard** [comment]
The trick is to do it this way: 
```
<div masonry>
   <div class="masonry-item">
      <your-own-directive></your-own-directive>
   </div>
</div>
```

**Comment by passy** [comment]
Thanks for your input, @wembernard. Closing now as there was no follow-up from OP.
