### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by alapasset** [passy/angular-masonry#154]
Hello,

Thx for your work, but i have a probleme with it. See my code :    
        
```javascript
<masonry column-width="200">
      <div class="masonry-brick" ng-repeat="news in newsList">
                 <news-item news="news" view-mode="viewMode"></news-item>
       </div>
</masonry>
```

But the width of columns is not correct in view :

![image](https://cloud.githubusercontent.com/assets/8247042/12321033/4494d008-baac-11e5-9b0d-65ab5eb96e45.png)

Can you help me please ?

**Comment by Taewa** [comment]
It didnt work for me neither. I just added css to '.masonry-brick'.
`.masonry-brick{width:25%;}`
