### ISSUE TITLE
getSize is not a function

### ISSUE THREAD

**Issue by Taewa** [passy/angular-masonry#156]
Hello.
I am using Ionic and want to use masonry.
Here is what I included to index.html

	<script src="lib/jquery/dist/jquery.js"></script>
	<script src="lib/jquery-bridget/jquery-bridget.js"></script>
	<script src="lib/ev-emitter/ev-emitter.js"></script>
	<script src="lib/desandro-matches-selector/matches-selector.js"></script>
	<script src="lib/fizzy-ui-utils/utils.js"></script>
	<script src="lib/outlayer/item.js"></script>
	<script src="lib/outlayer/outlayer.js"></script>
	<script src="lib/masonry/masonry.js"></script>
	<script src="lib/imagesloaded/imagesloaded.js"></script>

	
	<script src="lib/ionic/js/ionic.bundle.js"></script>
	

	
	<script src="lib/angular-masonry/angular-masonry.js"></script>

As you can see I replaced angular.js to ionic.bundle.js because angular is included in ionic.
And I get this error.
`TypeError: getSize is not a function`

I made sure all files are correctly included via chrome inspector.

**Comment by Taewa** [comment]
Ok, I don't know why I always resolve problem after I post question.

When I downloaded all dependencies through 
`bower install --save angular-masonry`
get-size.js was not included.

After I downloaded get-size
`bower install get-size`

It works.

**Comment by darrylivan** [comment]
I had the get-size component in my bower components, but it was not in the list of includes that I got from the example.  once i added the include, this problem was fixed for me.

**Comment by TaylorAckley** [comment]
Same thing happened to me.... included it right under jquery and now I have a clean console.

**Comment by JeffreyATW** [comment]
#165 should fix this.
