### ISSUE TITLE
without jquery

### ISSUE THREAD

**Issue by pliablepixels** [passy/angular-masonry#158]
Hi there, do you have any plans on releasing a version without jquery? Newer versions of masonry don't need jquery. Thank you!

**Comment by jodytate** [comment]
This is being discussed over in issue https://github.com/passy/angular-masonry/issues/40. To sum it up: angular-masonry can work without jQuery but the unit tests need to be brought up to speed.

**Comment by pliablepixels** [comment]
ok, thanks. I'll follow #40 and close this
