### ISSUE TITLE
Cannot call methods, i.e. $().masonry("layout")

### ISSUE THREAD

**Issue by kuyoonjo** [passy/angular-masonry#179]
Everything is OK but, when I try to go another page, the console outputs an error:

masonry not initialized. Cannot call methods, i.e. $().masonry("layout")

**Comment by armensg** [comment]
I get this issue too

**Comment by ghost** [comment]
Possible connection with this issue: https://github.com/desandro/masonry/issues/556
And this is how Desandro suggest to fix it: https://masonry.desandro.com/faq.html#error-cannot-call-methods-on-masonry-prior-to-initialization-attempted-to-call-___
