### ISSUE TITLE
Adjust bricks with change in heights of bricks, dynamically.

### ISSUE THREAD

**Issue by nikhilvm1993** [passy/angular-masonry#181]
I am using angular-masonry .is it possible to push down the brick, if above brick height increased?

**Comment by vmontazeri** [comment]
Were you able to fix this? I'm stuck with the same issue

**Comment by vmnikhil** [comment]
@vmontazeri , Whenever the layout needs to be refreshed, call $scope.$broadcast('masonry.reload');

Thats how i managed this task..

**Comment by vmontazeri** [comment]
Thanks! It worked.
