### ISSUE TITLE
loading remote images seems to not use imagesloaded correctly?

### ISSUE THREAD

**Issue by l0c0luke** [passy/angular-masonry#20]
Not sure if this is a problem in masonry or imagesloaded library ...

But I am using this to show items that include a remote link to a facebook image. It seemed to be overlapping always. My workaround was to change line 35 in your code to timeout for 500ms instead of 30.

Is this a horrible idea?

**Comment by brusacco** [comment]
http://stackoverflow.com/questions/3799134/how-to-get-final-url-after-following-http-redirections-in-pure-php
