### ISSUE TITLE
Masonry layouts vertically upon initial load then reorganizes horizontally.

### ISSUE THREAD

**Issue by RDash20** [passy/angular-masonry#39]
I'm running into some issues where then the page first renders my mason bricks, it lays out the mason bricks vertically like so. 
[[brick 1]]
[[brick 2]]

Then an instant later it lays out the bricks horizontally. 

[[brick 1]] [[brick 2]]

This cause a flickering on every page load. In my project, my bricks are Angular directives. And Angular is rendering out the bricks before Masonry has a chance to lay them out. Have you run into this issues before?Have you tested this library on directives instead of just images?

**Comment by yellowiscool** [comment]
@jawache No, I use Masonry without this plugin. It's less beautiful though.

**Comment by justincoh** [comment]
I know this is closed, but for anyone else who stumbles across this you have to be **very** careful with async issues using angular masonry, particularly with regard to imagesLoaded and ng-src, or if you're using any kind of ng-style, as the masonry bricks will sometimes render before angular has had a chance to set those properties.

**Comment by duhaime** [comment]
In my case, I just inlined a `class="not-loaded"` on my masonry items, and set `display:none` on that css. Then, once the bricks are loaded, angular-masonry gave those bricks the `loaded` class, and one can set `display:block` on the `loaded` class to prevent any flickering.

**Comment by vinay13** [comment]
@passy  did you find a solution? I'm having the same issues.
