### ISSUE TITLE
Work without needing jQuery

### ISSUE THREAD

**Issue by dremonkey** [passy/angular-masonry#40]
Curious as to what your thoughts are on making this work without needing jQuery. I have a working fork if you would like to take a look. 

https://github.com/dremonkey/angular-masonry/compare/nojquery

**Comment by TimPetricola** [comment]
Any news on this one?

**Comment by macneib** [comment]
Day job called. Pretty sure I won't have time for a while.

**Comment by simonsayscode** [comment]
Is there any progress on this? It seems like it's a pretty innocuous change since you don't need to depend on jQuery to utilize Masonry directly.

**Comment by passy** [comment]
Still happy to take PRs, @simonsayscode. :)
