### ISSUE TITLE
Error: element.masonry is not a function

### ISSUE THREAD

**Issue by ChrisCinelli** [passy/angular-masonry#54]
The markup:

```
<div class="discovery" data-ng-controller="ResourcesController" data-ng-init="find()"> 
    <div masonry>
        <div class="masonry-brick card {{res.type}}" data-ng-repeat="res in resources" ng-switch on="res.type">

            Add just water...  
        </div>   
    </div>
</div>
```

"Error: element.masonry is not a function
preLink@http://127.0.0.1:3000/js/angular-masonry.js:133
A@http://127.0.0.1:3000/lib/angular/angular.min.js:49
h@http://127.0.0.1:3000/lib/angular/angular.min.js:43
A@http://127.0.0.1:3000/lib/angular/angular.min.js:49
h@http://127.0.0.1:3000/lib/angular/angular.min.js:43
Y/<@http://127.0.0.1:3000/lib/angular/angular.min.js:42
updateView@http://127.0.0.1:3000/lib/angular-ui-router/release/angular-ui-router.js:2290
$ViewDirective/directive.compile/</eventHook@http://127.0.0.1:3000/lib/angular-ui-router/release/angular-ui-router.js:2224
Ed/this.$get</h.prototype.$broadcast@http://127.0.0.1:3000/lib/angular/angular.min.js:107
transitionTo/$state.transition<@http://127.0.0.1:3000/lib/angular-ui-router/release/angular-ui-router.js:1822
Cd/e/l.promise.then/C@http://127.0.0.1:3000/lib/angular/angular.min.js:94
Cd/f/<.then/<@http://127.0.0.1:3000/lib/angular/angular.min.js:95
Ed/this.$get</h.prototype.$eval@http://127.0.0.1:3000/lib/angular/angular.min.js:104
Ed/this.$get</h.prototype.$digest@http://127.0.0.1:3000/lib/angular/angular.min.js:102
Ed/this.$get</h.prototype.$apply@http://127.0.0.1:3000/lib/angular/angular.min.js:105
e/h<@http://127.0.0.1:3000/lib/angular/angular.min.js:115
e@http://127.0.0.1:3000/lib/angular/angular.min.js:33
gd/h.defer/c<@http://127.0.0.1:3000/lib/angular/angular.min.js:37
" "<div masonry="">"

**Comment by poolebu** [comment]
Have the same issue, a list of the required dependencies is needed

**Comment by poolebu** [comment]
this worked for me: http://stackoverflow.com/questions/21962972/getting-angular-masonry-to-work-it-says-it-has-no-method-imagesloaded

**Comment by maiamachine** [comment]
Posting this here as I struggled with this for awhile before realizing there were a whole bunch of dependencies I needed to add. After adding them everything works great. So you don't have to go digging, here's this:

        <script src="bower_components/jquery/dist/jquery.js"></script>
        <script src="bower_components/jquery-bridget/jquery.bridget.js"></script>
        <script src="bower_components/get-style-property/get-style-property.js"></script>
        <script src="bower_components/get-size/get-size.js"></script>
        <script src="bower_components/eventEmitter/EventEmitter.js"></script>
        <script src="bower_components/eventie/eventie.js"></script>
        <script src="bower_components/doc-ready/doc-ready.js"></script>
        <script src="bower_components/matches-selector/matches-selector.js"></script>
        <script src="bower_components/outlayer/item.js"></script>
        <script src="bower_components/outlayer/outlayer.js"></script>
        <script src="bower_components/masonry/masonry.js"></script>
        <script src="bower_components/imagesloaded/imagesloaded.js"></script>

        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.0/angular.min.js"></script>
        <script src="angular-masonry.js"></script>

**Comment by codeit-ninja** [comment]
This fixed it for me. Just set the attribute `load-images="false"`
