### ISSUE TITLE
Make Dependencies Clear in Readme

### ISSUE THREAD

**Issue by kencaron** [passy/angular-masonry#60]
When I stumbled on this I assumed it was a standalone rewrite similar to [UI Bootstrap](http://angular-ui.github.io/bootstrap/).  

Especially for those new to Masonry, It'd be helpful to note that this module has hard requirements for:
- jQuery
- packaged Masonry
- packaged imagesloaded

**Comment by arsenetoumani** [comment]
Doesn't hurt to add a depency section. Thanks for the module though.
