### ISSUE TITLE
 Error when changing the height of any item selector

### ISSUE THREAD

**Issue by wondersofttech** [passy/angular-masonry#7]
I have a masonry-brick which can change the height of any item selector in this script whenever I click a 'More/Less' button. But when I click this button, it causes some errors of other masonry-brick scripts which is in inside each other, so how can I fix this issue, please help me asap?

**Comment by beeseenmedia** [comment]
I have an issue in which i have a masonry-brick and within i have a ng-show.  when that ng-show is triggered the size changes but the layout is not changed
