### ISSUE TITLE
CDN?

### ISSUE THREAD

**Issue by dan-santana** [passy/angular-masonry#81]
It would be cool if this project was also hosted on cdnjs or JsDelivr.

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage

Example https://cdn.jsdelivr.net/npm/jquery@3.1.1
Example directory listing https://cdn.jsdelivr.net/npm/jquery@3.1.1/
