### ISSUE TITLE
Does it work with non-image content?

### ISSUE THREAD

**Issue by kpgarrod** [passy/angular-masonry#89]
I am trying to use this with angular-material, to wrap md-cards across rows. I'm getting some errors. Can angular-masonry wrap non-images? BTW, It looks spectacular!

**Comment by jodytate** [comment]
came here looking for non-image implementation details and wolf gif. was not disappointed.

**Comment by DanielMSchmidt** [comment]
@kpgarrod Sorry, somehow I didn't get the notification. To my mind there should be no concerns regarding compatibility, although I haven't used both in the same project by now. What do you exactly mean by integration?
